DB = './score.txt'

[testing]
DB = './score.txt'
score_update_delay = 60
message_read_delay = 1
waiting_for_names = true
confirmed = false
quick_start=false

[quick_start]
DB = './score.txt'
score_update_delay = 60
message_read_delay = 1
waiting_for_names = false
confirmed = true
quick_start=true